### ISSUE TITLE
can not install simpeg

### ISSUE THREAD

**Issue by MsBruce** [simpeg/simpeg#1263]
![1](https://github.com/simpeg/simpeg/assets/19356568/840c3d06-2768-4d05-aae5-a168c3979098)
![2](https://github.com/simpeg/simpeg/assets/19356568/bf72605a-c390-4abd-b06a-c9034c9242ed)

**Comment by MsBruce** [comment]
When I tried installing the source code, I still prompted an error
![3](https://github.com/simpeg/simpeg/assets/19356568/304b3e71-8ed1-4119-8b0b-be118e56ba1a)

**Comment by jcapriot** [comment]
Cython recently release its 3.0.0 update, so there was one line in discretize that needed to be updated. It has been fixed in that repo already, but it has not been pushed to pypi just yet. In the meantime, I recommend installing everything through anaconda (likely mamba forge) and you should not have this issue.

**Comment by MsBruce** [comment]
> 
Thank you very much. And when I use andconda to install it ,I still encountering some difficulties， could you help me? 
![4](https://github.com/simpeg/simpeg/assets/19356568/622374de-a0f9-484e-a599-d261ad9d19f3)
![5](https://github.com/simpeg/simpeg/assets/19356568/14bdff89-0250-4689-8fef-ac2a0265193d)

![6](https://github.com/simpeg/simpeg/assets/19356568/166f2623-7d67-4c71-a1fb-b4eb54b2e26c)
